customhost = "employee.curhywyfpta2.ap-south-1.rds.amazonaws.com"
customuser = "krishna"
custompass = "People$987"
customdb = "employee"
custombucket = "krishawsenterprise"
customregion = "ap-south-1"
